# Generated by Django 5.0.2 on 2024-03-04 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='groups',
        ),
        migrations.AddField(
            model_name='subjectrealization',
            name='groups',
            field=models.ManyToManyField(to='api.group'),
        ),
    ]
