# Generated by Django 5.0.2 on 2024-04-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Administrator'), ('2', 'Teacher'), ('3', 'Student')], default=1, max_length=20, verbose_name='Type'),
        ),
    ]
