# Generated by Django 5.0.2 on 2024-03-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_subject_groups_subjectrealization_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('1', 'Administrator'), ('2', 'Teacher'), ('3', 'Student')], default=1, max_length=20),
        ),
    ]
