# Generated by Django 5.0.2 on 2024-03-05 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='teacher_replacement',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.teacher'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject_realization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjectrealization'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(choices=[(1, '+'), (2, 'Н'), (3, 'П'), (4, 'Б')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.RemoveField(
            model_name='subject',
            name='course_id',
        ),
        migrations.AlterField(
            model_name='subjectrealization',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.AutoField(db_index=True, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='subject',
            name='course_id',
            field=models.ManyToManyField(to='api.course'),
        ),
    ]
