# Generated by Django 5.0.2 on 2024-05-16 04:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_attendance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='zk',
            field=models.CharField(default=2020, max_length=255, verbose_name='Номер зачетной кнжики'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='groups',
            field=models.ManyToManyField(to='api.group', verbose_name='Группы'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='isComplete',
            field=models.BooleanField(default=False, verbose_name='Подтвержден?'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='location',
            field=models.CharField(max_length=255, verbose_name='Место проведения'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='subject_realization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subjectrealization', verbose_name='Реализация предмета'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='teacher_replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.teacher', verbose_name='Замена'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_end',
            field=models.TimeField(verbose_name='Время конца'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_start',
            field=models.TimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='attendance_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.attendance', verbose_name='Занятие'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='last_edit_time',
            field=models.TimeField(auto_now=True, verbose_name='Последние изменение'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(choices=[('1', '+'), ('2', 'Н'), ('3', 'П'), ('4', 'Б')], default=1, max_length=1, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='attendancereport',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='course',
            name='faculty_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.faculty', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='student',
            name='isHeadman',
            field=models.BooleanField(default=False, verbose_name='Староста?'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectrealization',
            name='subject_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='subjectrealization',
            name='teacher_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AlterField(
            model_name='subjectrealization',
            name='type',
            field=models.CharField(choices=[('лекция', 'лекция'), ('практика', 'практика')], default='лекция', max_length=20, verbose_name='Тип'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
