# Generated by Django 5.0.2 on 2024-03-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_attendance_teacher_replacement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='status',
            field=models.CharField(choices=[('1', '+'), ('2', 'Н'), ('3', 'П'), ('4', 'Б')], default=1, max_length=1),
        ),
        migrations.AlterField(
            model_name='subjectrealization',
            name='type',
            field=models.CharField(choices=[('1', 'lection'), ('2', 'practice')], default=1, max_length=20),
        ),
    ]
