# Generated by Django 5.0.2 on 2024-05-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_zk_alter_attendance_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='scientific_title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Звание'),
        ),
    ]
