# Generated by Django 5.0.2 on 2024-05-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_teacher_job_title_teacher_scientific_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='year',
            field=models.CharField(default=2014, max_length=4, verbose_name='Год создания'),
            preserve_default=False,
        ),
    ]
