# Generated by Django 5.0.2 on 2024-03-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_attendance_attendance_date_attendance_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='time_start',
            field=models.TimeField(),
        ),
    ]
