# Generated by Django 5.0.2 on 2024-03-06 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_attendance_teacher_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='teacher_replacement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.teacher'),
        ),
    ]
