# Generated by Django 5.0.2 on 2024-03-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_attendance_teacher_replacement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrealization',
            name='type',
            field=models.CharField(choices=[('лекция', 'лекция'), ('практика', 'практика')], default=1, max_length=20),
        ),
    ]
