# Generated by Django 5.0.2 on 2024-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_subjectrealization_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrealization',
            name='type',
            field=models.CharField(choices=[('лекция', 'лекция'), ('практика', 'практика')], default='лекция', max_length=20),
        ),
    ]
