# Generated by Django 5.0.2 on 2024-03-08 18:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_subject_course_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='last_edit_time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
