# Generated by Django 5.0.2 on 2024-03-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_attendancereport_last_edit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancereport',
            name='last_edit_time',
            field=models.TimeField(auto_now=True),
        ),
    ]
