# Generated by Django 5.0.2 on 2024-03-10 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_attendancereport_last_edit_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancereport',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.group'),
        ),
    ]
