# Generated by Django 5.0.2 on 2024-03-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_attendancereport_iscomplete_alter_student_group_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancereport',
            name='isComplete',
        ),
        migrations.AddField(
            model_name='attendance',
            name='isComplete',
            field=models.BooleanField(default=False),
        ),
    ]
